# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
      reviewers:
        - 'jds691'
      directory: "/"
      schedule:
          interval: "weekly"
      rebase-strategy: "disabled"
      groups:
          kotlin:
              patterns:
                - 'org.jetbrains.kotlin*'
              exclude-patterns:
                - 'org.jetbrains.kotlinx*'
           hilt:
               patterns:
                 - 'com.google.dagger*'
           data-store:
               patterns:
                 - 'androidx.datastore*'
           room:
               patterns:
                 - 'androidx.room*'
  

    - package-ecosystem: "github-actions"
      reviewers:
        - 'jds691'
      directory: "/"
      schedule:
          interval: "daily"
      rebase-strategy: "disabled"
